apiVersion: v2
name: authelia-oidc-operator
description: A Kubernetes operator that manages OIDC client configurations for Authelia
type: application
version: 0.1.5
appVersion: "0.1.6"
kubeVersion: ">=1.28.0-0"
home: https://github.com/fredericrous/authelia-oidc-operator
sources:
  - https://github.com/fredericrous/authelia-oidc-operator
maintainers:
  - name: fredericrous
    url: https://github.com/fredericrous
keywords:
  - authelia
  - oidc
  - operator
  - kubernetes
  - authentication
